### ISSUE TITLE
Add Delphinus support - installation as a package

### ISSUE THREAD

**Issue by Pawe1** [hprose/hprose-delphi#6]
:bulb: **Idea: add Delphinus support**

Advantages:
- easier installation
- spreading a word about Hprose in new places
- allow to add Hprose as a dependency for other Delphinus packages.

[Here is some draft without compilation of packages](https://github.com/Pawe1/hprose-delphi/tree/Delphinus)
The line with keyword "Delphinus-Support" in readme is required to find repository via GitHub API.

**Comment by andot** [comment]
Very Cool!
