### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by edwinyzh** [hprose/hprose-delphi#7]
This is a very interesting project! Two questions if you don't mind:

1. The Delphi implementation has the client only, but no server implementation, right?
2. Do you have an example? 

Thanks.

**Comment by andot** [comment]
1. Right now, there is only client.
2. The documents and examples has not completed. The old version documents is here: https://github.com/andot/hprose/blob/master/doc/1.3/pdf/pascal.pdf

**Comment by shayneoneill** [comment]
Is there an english version of that document? I cant make heads or tails of it :(

**Comment by andot** [comment]
There is only a chinese document right now.
