### ISSUE TITLE
Compilation issue - Lazarus 2.2.0 with FPC 3.2.2

### ISSUE THREAD

**Issue by MFernstrom** [hprose/hprose-delphi#9]
I tried installing the HProse Synapse version on Lazarus 2.2.0 with FPC 3.2.2 and got an error.

`HproseCommon.pas(1371,15) Error: Can't determine which overloaded function to call`

This is the line `Result := Supports(nil, IID, AIntf)`

**Comment by MFernstrom** [comment]
That worked, next error I get is `HproseCommon.pas(4925,55) Error: Can't assign values to const variable`

And the line is `VarObjectType.DispInvoke(PVarData(Dest), TVarData(Source), CallDesc, Params)`

**Comment by andot** [comment]
Fixed now.
